# docker-compose.yml

version: "3"

services:

  pocketbase:
    container_name: pocketbase
    image: spectado/pocketbase
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./pb/pb_data:/pb_data
      - ./pb/pb_hooks:/pb_hooks
      - ./pb/pb_migrations:/pb_migrations

  smtp:
    container_name: smtp
    image: marlonb/mailcrab:latest
    restart: unless-stopped
    ports:
      - 1025:1025
      - 1080:1080
